ColinaDoSol/urls.py
from django.urls import path, reverse_lazy

from django.contrib.auth import views as auth_views
from .views.site import *
from .views.business import *
from .views.user import *
from .views.store import *
from .views.anuncios import *
from .views.dashboard import *
from .views.content import *

app_name = 'ColinaDoSol'

urlpatterns = [
    path('', index, name='index'),
    path('mapa', mapa, name='mapa'),
    path('dashboard/', dboard_main, name='dboard_main'),
    path('dashboard/perfil/resetPass', user_reset_password, name='dboard_reset_pass'),
    path('dashboard/perfil', dboard_perfil, name='dboard_perfil'),
    path('dashboard/lojistas', dboard_lojistas, name='dboard_lojistas'),
    path('dashboard/novoUser', admin_required(dboard_novo_user), name='dboard_novo_user'),
    path('dashboard/lojas', dboard_lojas, name='dboard_lojas'),
    path('dashboard/anuncios', dboard_anuncios, name='dboard_anuncios'),
    path('dashboard/novaLoja', admin_required(dboard_nova_loja), name='dboard_nova_loja'),
    path('dashboard/novoProduto', dboard_new_product, name='dboard_novo_produto'),
    path('dashboard/editarProduto/<int:produto_id>', dboard_edit_product, name='dboard_editar_produto'),
    path('dashboard/deleteProduto/<int:produto_id>', dboard_delete_product, name='dboard_delete_produto'),
    path('dashboard/novoAnuncio', admin_required(dboard_novo_anuncio), name='dboard_novo_anuncio'),
    path('dashboard/editarAnuncio/<int:anuncio_id>', dboard_editar_anuncio, name='dboard_editar_anuncio'),
    path('dashboard/deleteAnuncio/<int:anuncio_id>', dboard_delete_anuncio, name='dboard_delete_anuncio'),
    path('dashboard/editar/<int:store_id>', dboard_editar_loja, name='dboard_editar_loja'),
    path('dashboard/deleteUser/<int:user_id>', dboard_delete_user, name='dboard_delete_user'),
    path('dashboard/editarUser/<int:user_id>', dboard_editar_user, name='dboard_editar_lojista'),
    path('dashboard/delete/<int:store_id>', dboard_delete_loja, name='dboard_delete_loja'),
    path('login', login_user, name='login'),
    path('logout', logout_user, name='logout'),
    path('businesses', businesses, name='businesses'),
    path('delete/businesses/<int:business_id>', delete_business, name='delete_businesses'),
    path('logs', dboard_logs, name='logs'),
    path('404', custom_404_view, name='custom_404'),
    path('dashboard/content', content, name='content'),
    path('dashboard/content_edit', edit_content, name='edit_content'),
    path('dashboard/content_slider_images', sliderImagesList, name='sliderImagesList'),
    path('dashboard/atualizar_ordem/', atualizar_ordem, name='atualizar_ordem'),
    path('dashboard/adicionar_imagem/', adicionar_imagem, name='adicionar_imagem'),
    path('dashboard/excluir_imagemexcluir_imagem/<int:imagem_id>', excluir_imagem, name='excluir_imagem'),

    # Change Password
    path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='ColinaDoSol/Dashboard/Users/change-password.html',
        success_url='/'), name='change_password'),

    path('password-reset/', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy("ColinaDoSol:password_reset_done"),
        template_name="ColinaDoSol/PasswordManagement/password_reset.html",
        email_template_name='ColinaDoSol/PasswordManagement/password_reset_email.html'
    ), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='ColinaDoSol/PasswordManagement/password_reset_done.html'
    ), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy("ColinaDoSol:password_reset_complete"),
        template_name='ColinaDoSol/PasswordManagement/password_reset_confirm.html'
    ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='ColinaDoSol/PasswordManagement/password_reset_complete.html'
    ), name='password_reset_complete'),
]

prototipo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'ColinaDoSol.views.site.custom_404_view'

urlpatterns = [
    path('', include('ColinaDoSol.urls')),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ColinaDoSol/models.py
import os

from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.conf import settings


class Business(models.Model):
    business = models.CharField(max_length=100)

    def __str__(self):
        return self.business


def get_image_path(instance, filename):
    ext = os.path.splitext(filename)[1]
    filename = f"id{instance.store_num}{ext}"
    return os.path.join('storeLogo/', filename)


class Store(models.Model):
    store_num = models.IntegerField(unique=True)
    image = models.ImageField(upload_to=get_image_path)
    brand = models.CharField('Nome loja', max_length=256)
    business = models.ForeignKey(Business, on_delete=models.DO_NOTHING, null=True)
    phoneNum = models.CharField('Contacto telefónico', max_length=12)
    email = models.CharField('E-mail', max_length=256)
    description = models.TextField('Descrição da loja')
    facebookLink = models.CharField('Link do Facebook', max_length=256, null=True, blank=True)
    instagramLink = models.CharField('Link do Instagram', max_length=256, null=True, blank=True)
    linkedinLink = models.CharField('Link do Linkedin', max_length=256, null=True, blank=True)
    twitterLink = models.CharField('Link do Twitter', max_length=256, null=True, blank=True)
    websiteLink = models.CharField('Link do Website', max_length=256, null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.brand


class OperatingHours(models.Model):
    WEEKDAYS = (
        ('segunda', 'Segunda-feira'),
        ('terca', 'Terça-feira'),
        ('quarta', 'Quarta-feira'),
        ('quinta', 'Quinta-feira'),
        ('sexta', 'Sexta-feira'),
        ('sabado', 'Sábado'),
        ('domingo', 'Domingo'),
        ('feriados', 'Feriados')
    )

    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    weekday = models.CharField(max_length=10, choices=WEEKDAYS)
    opening_time = models.TimeField('Horario de abertura', null=True, blank=True)
    closing_time = models.TimeField('Horario de fecho', null=True, blank=True)
    lunch_start_time = models.TimeField('Início de almoço', null=True, blank=True)
    lunch_end_time = models.TimeField('Fim de almoço', null=True, blank=True)



class Product(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    name = models.CharField('Nome', max_length=128)
    description = models.CharField('Descrção', max_length=512)
    image = models.ImageField(upload_to='uploads/products')


class UserAction(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    action = models.CharField(max_length=1100)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} {self.action} {self.date}'


class User(AbstractUser):
    class Role(models.TextChoices):
        ADMIN = "ADMIN", 'Admin'
        LOJISTA = "LOJISTA", 'Lojista'

    role = models.CharField(max_length=100, choices=Role.choices)
    phone_number = models.CharField(max_length=20, blank=True)
    is_first_login = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Announcement(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title


class SiteConfiguration(models.Model):
    logo = models.ImageField(upload_to='content/ColinaDoSol/img/')
    description = models.TextField()
    facebookLink = models.CharField('Link do Facebook', max_length=256, null=True, blank=True)
    instagramLink = models.CharField('Link do Instagram', max_length=256, null=True, blank=True)


class Imagem(models.Model):
    imagem = models.ImageField(upload_to='uploads/products')
    timestamp = models.DateTimeField(auto_now_add=True)
    ordem = models.PositiveIntegerField(default=0)


class AccessToken(models.Model):
    token = models.CharField(max_length=255)

ColinaDoSol/views/dashboard.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from ColinaDoSol.models import Announcement, User, Store


@login_required
def dboard_main(request):
    anunciosList = Announcement.objects.all()

    if request.user.role == User.Role.ADMIN or request.user.is_superuser:
        lojasList = Store.objects.all()
        lojistas = User.objects.filter(role=User.Role.LOJISTA)
        context = {'lojasList': lojasList[:3], 'lojistas': lojistas[:3], 'anuncios': anunciosList, 'current_page': 'dashboard'}

    else:
        lojasList = Store.objects.filter(user=request.user)
        context = {'lojasList': lojasList[:3], 'anuncios': anunciosList, 'current_page': 'dashboard'}
    return render(request, 'ColinaDoSol/Dashboard/dboard-main.html', context)

templates/ColinaDoSol/Dashboard/DashboardElements/adminListItem.html
{% for admin in admins %}
    <div class="card mb-3 m-auto">
    <div class="d-flex justify-content-between card-header">
        <h5 >{{ admin }}</h5>

            <a href="{% url 'ColinaDoSol:dboard_editar_lojista' admin.id %}"
               class="btn btn-outline-success"><i
                    class="fa-solid fa-pen-to-square form-input-icon"></i>Editar</a>
    </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <p><strong>Username:</strong> {{ admin.username }}</p>
                    <p><strong>Email:</strong> {{ admin.email }}</p>
                </div>
                <div class="col-md-6">
                    <p><strong>Loja:</strong> {{ admin.store_set.first }} ( Nº{{ admin.store_set.first.store_num }}
                        )</p>
                    <p><strong>Data de Criação:</strong> {{ admin.date_joined }}</p>

                </div>
            </div>
        </div>
    </div>
{% endfor %}

templates/ColinaDoSol/Dashboard/DashboardElements/anuncioListItem.html
{% for anuncio in anuncios %}
    <div class="card mb-3 m-auto">
        <div class="d-flex justify-content-between card-header">
                <h5 class="">{{ anuncio.title }}</h5>
            {% if request.user.role == "ADMIN" or request.user.is_superuser %}
                <a href="{% url 'ColinaDoSol:dboard_editar_anuncio' anuncio.id %}"
                   class="btn btn-outline-success"><i
                        class="fa-solid fa-pen-to-square form-input-icon"></i>Editar</a>
            {% endif %}
        </div>
        <div class="card-body">
            <p class="card-text">{{ anuncio.text|safe }}</p>
        </div>
        <div class="card-footer text-muted">
            <div class="announcement-details">
                <p>Por: {{ anuncio.user }}</p>
                <p>{{ anuncio.creation_date }}</p>
            </div>
        </div>
    </div>
{% endfor %}

templates/ColinaDoSol/Dashboard/DashboardElements/lojistaListItem.html
{% for lojista in lojistas %}
    <div class="card mb-3 m-auto">
    <div class="d-flex justify-content-between card-header">
        <h5 >{{ lojista }}</h5>

            <a href="{% url 'ColinaDoSol:dboard_editar_lojista' lojista.id %}"
               class="btn btn-outline-success"><i
                    class="fa-solid fa-pen-to-square form-input-icon"></i>Editar</a>
    </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <p><strong>Username:</strong> {{ lojista.username }}</p>
                    <p><strong>Email:</strong> {{ lojista.email }}</p>
                </div>
                <div class="col-md-6">
                    <p><strong>Loja:</strong> {{ lojista.store_set.first }} ( Nº{{ lojista.store_set.first.store_num }}
                        )</p>
                    <p><strong>Data de Criação:</strong> {{ lojista.date_joined }}</p>

                </div>
            </div>
        </div>
    </div>
{% endfor %}

templates/ColinaDoSol/Dashboard/DashboardElements/productListItem.html
{% for product in productList %}
    <div class="card mb-3 m-auto" style="max-width: 540px;">
        <div class="row g-0">
            <div class="col-md-4 d-flex">
                <img src="{{ product.image.url }}" class="img-fluid m-auto" alt="..."
                     style="padding: 16px">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <div class="mb-5">
                        <h5 class="card-title">{{ product.brand }}</h5>
                        <p class="card-text">{{ product.description }}</p>
                    </div>
                    <div>
                        <a href="{% url 'ColinaDoSol:dboard_editar_produto' product.id %}"
                           class="btn btn-outline-success"><i
                                class="fa-solid fa-pen-to-square form-input-icon"></i>Editar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}

templates/ColinaDoSol/Dashboard/DashboardElements/storeListItem.html
{% for loja in lojasList %}
    <div class="card mb-3 m-auto" style="max-width: 540px;">
        <div class="row g-0">
            <img src="{{ loja.image.url }}" class="img-fluid m-auto" alt="..."
                         style="padding: 16px; max-height: 300px; object-fit: contain">
        </div>
            <div class="row g-0">
                <div class="col">
                    <div class="card-body">
                        <div class="mb-5">
                            <h5 class="card-title">{{ loja.brand }}</h5>
                            <p class="card-text">{{ loja.description }}</p>
                        </div>
                        <div>
                            <a href="{% url 'ColinaDoSol:dboard_editar_loja' loja.id %}"
                               class="btn btn-outline-success"><i
                                    class="fa-solid fa-pen-to-square form-input-icon"></i>Editar</a>
                        </div>
                    </div>
                </div>
            </div>

    </div>
{% endfor %}