ColinaDoSol/urls.py
from django.urls import path, reverse_lazy

from django.contrib.auth import views as auth_views
from .views.site import *
from .views.business import *
from .views.user import *
from .views.store import *
from .views.anuncios import *
from .views.dashboard import *
from .views.content import *

app_name = 'ColinaDoSol'

urlpatterns = [
    path('', index, name='index'),
    path('mapa', mapa, name='mapa'),
    path('dashboard/', dboard_main, name='dboard_main'),
    path('dashboard/perfil/resetPass', user_reset_password, name='dboard_reset_pass'),
    path('dashboard/perfil', dboard_perfil, name='dboard_perfil'),
    path('dashboard/lojistas', dboard_lojistas, name='dboard_lojistas'),
    path('dashboard/novoUser', admin_required(dboard_novo_user), name='dboard_novo_user'),
    path('dashboard/lojas', dboard_lojas, name='dboard_lojas'),
    path('dashboard/anuncios', dboard_anuncios, name='dboard_anuncios'),
    path('dashboard/novaLoja', admin_required(dboard_nova_loja), name='dboard_nova_loja'),
    path('dashboard/novoProduto', dboard_new_product, name='dboard_novo_produto'),
    path('dashboard/editarProduto/<int:produto_id>', dboard_edit_product, name='dboard_editar_produto'),
    path('dashboard/deleteProduto/<int:produto_id>', dboard_delete_product, name='dboard_delete_produto'),
    path('dashboard/novoAnuncio', admin_required(dboard_novo_anuncio), name='dboard_novo_anuncio'),
    path('dashboard/editarAnuncio/<int:anuncio_id>', dboard_editar_anuncio, name='dboard_editar_anuncio'),
    path('dashboard/deleteAnuncio/<int:anuncio_id>', dboard_delete_anuncio, name='dboard_delete_anuncio'),
    path('dashboard/editar/<int:store_id>', dboard_editar_loja, name='dboard_editar_loja'),
    path('dashboard/deleteUser/<int:user_id>', dboard_delete_user, name='dboard_delete_user'),
    path('dashboard/editarUser/<int:user_id>', dboard_editar_user, name='dboard_editar_lojista'),
    path('dashboard/delete/<int:store_id>', dboard_delete_loja, name='dboard_delete_loja'),
    path('login', login_user, name='login'),
    path('logout', logout_user, name='logout'),
    path('businesses', businesses, name='businesses'),
    path('delete/businesses/<int:business_id>', delete_business, name='delete_businesses'),
    path('logs', dboard_logs, name='logs'),
    path('404', custom_404_view, name='custom_404'),
    path('dashboard/content', content, name='content'),
    path('dashboard/content_edit', edit_content, name='edit_content'),
    path('dashboard/content_slider_images', sliderImagesList, name='sliderImagesList'),
    path('dashboard/atualizar_ordem/', atualizar_ordem, name='atualizar_ordem'),
    path('dashboard/adicionar_imagem/', adicionar_imagem, name='adicionar_imagem'),
    path('dashboard/excluir_imagemexcluir_imagem/<int:imagem_id>', excluir_imagem, name='excluir_imagem'),

    # Change Password
    path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='ColinaDoSol/Dashboard/Users/change-password.html',
        success_url='/'), name='change_password'),

    path('password-reset/', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy("ColinaDoSol:password_reset_done"),
        template_name="ColinaDoSol/PasswordManagement/password_reset.html",
        email_template_name='ColinaDoSol/PasswordManagement/password_reset_email.html'
    ), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='ColinaDoSol/PasswordManagement/password_reset_done.html'
    ), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy("ColinaDoSol:password_reset_complete"),
        template_name='ColinaDoSol/PasswordManagement/password_reset_confirm.html'
    ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='ColinaDoSol/PasswordManagement/password_reset_complete.html'
    ), name='password_reset_complete'),
]

prototipo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'ColinaDoSol.views.site.custom_404_view'

urlpatterns = [
    path('', include('ColinaDoSol.urls')),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ColinaDoSol/models.py
import os

from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.conf import settings


class Business(models.Model):
    business = models.CharField(max_length=100)

    def __str__(self):
        return self.business


def get_image_path(instance, filename):
    ext = os.path.splitext(filename)[1]
    filename = f"id{instance.store_num}{ext}"
    return os.path.join('storeLogo/', filename)


class Store(models.Model):
    store_num = models.IntegerField(unique=True)
    image = models.ImageField(upload_to=get_image_path)
    brand = models.CharField('Nome loja', max_length=256)
    business = models.ForeignKey(Business, on_delete=models.DO_NOTHING, null=True)
    phoneNum = models.CharField('Contacto telefónico', max_length=12)
    email = models.CharField('E-mail', max_length=256)
    description = models.TextField('Descrição da loja')
    facebookLink = models.CharField('Link do Facebook', max_length=256, null=True, blank=True)
    instagramLink = models.CharField('Link do Instagram', max_length=256, null=True, blank=True)
    linkedinLink = models.CharField('Link do Linkedin', max_length=256, null=True, blank=True)
    twitterLink = models.CharField('Link do Twitter', max_length=256, null=True, blank=True)
    websiteLink = models.CharField('Link do Website', max_length=256, null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.brand


class OperatingHours(models.Model):
    WEEKDAYS = (
        ('segunda', 'Segunda-feira'),
        ('terca', 'Terça-feira'),
        ('quarta', 'Quarta-feira'),
        ('quinta', 'Quinta-feira'),
        ('sexta', 'Sexta-feira'),
        ('sabado', 'Sábado'),
        ('domingo', 'Domingo'),
        ('feriados', 'Feriados')
    )

    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    weekday = models.CharField(max_length=10, choices=WEEKDAYS)
    opening_time = models.TimeField('Horario de abertura', null=True, blank=True)
    closing_time = models.TimeField('Horario de fecho', null=True, blank=True)
    lunch_start_time = models.TimeField('Início de almoço', null=True, blank=True)
    lunch_end_time = models.TimeField('Fim de almoço', null=True, blank=True)



class Product(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    name = models.CharField('Nome', max_length=128)
    description = models.CharField('Descrção', max_length=512)
    image = models.ImageField(upload_to='uploads/products')


class UserAction(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    action = models.CharField(max_length=1100)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} {self.action} {self.date}'


class User(AbstractUser):
    class Role(models.TextChoices):
        ADMIN = "ADMIN", 'Admin'
        LOJISTA = "LOJISTA", 'Lojista'

    role = models.CharField(max_length=100, choices=Role.choices)
    phone_number = models.CharField(max_length=20, blank=True)
    is_first_login = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Announcement(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title


class SiteConfiguration(models.Model):
    logo = models.ImageField(upload_to='content/ColinaDoSol/img/')
    description = models.TextField()
    facebookLink = models.CharField('Link do Facebook', max_length=256, null=True, blank=True)
    instagramLink = models.CharField('Link do Instagram', max_length=256, null=True, blank=True)


class Imagem(models.Model):
    imagem = models.ImageField(upload_to='uploads/products')
    timestamp = models.DateTimeField(auto_now_add=True)
    ordem = models.PositiveIntegerField(default=0)


class AccessToken(models.Model):
    token = models.CharField(max_length=255)

ColinaDoSol/views/dashboard.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from ColinaDoSol.models import Announcement, User, Store


@login_required
def dboard_main(request):
    anunciosList = Announcement.objects.all()

    if request.user.role == User.Role.ADMIN or request.user.is_superuser:
        lojasList = Store.objects.all()
        lojistas = User.objects.filter(role=User.Role.LOJISTA)
        context = {'lojasList': lojasList[:3], 'lojistas': lojistas[:3], 'anuncios': anunciosList, 'current_page': 'dashboard'}

    else:
        lojasList = Store.objects.filter(user=request.user)
        context = {'lojasList': lojasList[:3], 'anuncios': anunciosList, 'current_page': 'dashboard'}
    return render(request, 'ColinaDoSol/Dashboard/dboard-main.html', context)

ColinaDoSol/views/user.py
import os

from django.contrib import messages
from django.contrib.admin.models import LogEntry
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import SetPasswordForm
from django.core.mail import send_mail
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from ColinaDoSol.decorators import admin_required
from ColinaDoSol.models import User, UserAction


@admin_required
def dboard_novo_user(request):
    if request.method == "POST":
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        username = request.POST.get('username')
        # password = request.POST.get('password')
        password = User.objects.make_random_password()
        role_name = request.POST.get('role')

        if role_name == "ADMIN":
            user = User(
                first_name=first_name,
                last_name=last_name,
                email=email,
                username=username,
                role=User.Role.ADMIN
            )
        else:
            user = User(
                first_name=first_name,
                last_name=last_name,
                email=email,
                username=username,
                role=User.Role.LOJISTA
            )

        # send email
        recipient_email = [email]
        subject = 'Novo utilizador'
        message = f'Foi criado um novo utilizador com o username {username} e a password {password}.' \
                  f' \n ***Terá de alterar a sua password ao fazer o primeiro login***'

        send_mail(subject, message, os.environ.get('DEFAULT_FROM_EMAIL'), recipient_email)

        user.is_active = True
        user.set_password(password)
        user.save()

        action = 'Criou um novo utilizador {} com privilégios de {}'.format(user.username, user.role)
        user_action = UserAction(user=request.user, action=action)
        user_action.save()

        admins = User.objects.filter(role=User.Role.ADMIN)
        lojistas = User.objects.filter(role=User.Role.LOJISTA)

        context = {
            'admins': admins,
            'lojistas': lojistas,
            'current_page': 'lojistas'
        }

        return render(request, 'ColinaDoSol/Dashboard/Users/dboard-lojistas.html', context)
    return render(request, 'ColinaDoSol/Dashboard/Users/dboard-novo-user.html', {'current_page': 'lojistas'})


@login_required
def dboard_editar_user(request, user_id):
    user = get_object_or_404(User, id=user_id)
    # user = User.objects.get(id=request.user.id)

    utilizador = request.user

    if utilizador.role != utilizador.Role.ADMIN and not utilizador.is_superuser and utilizador.id != user.id:
        raise Http404("This page does not exist")

    if request.method == "POST":

        new_first_name = request.POST.get('first_name')
        new_last_name = request.POST.get('last_name')
        new_email = request.POST.get('email')
        new_username = request.POST.get('username')
        new_password = request.POST.get('password')

        changes = []

        if user.first_name != new_first_name:
            changes.append(f"<strong>Primeiro Nome:</strong> {user.first_name} -> {new_first_name}")

        if user.last_name != new_last_name:
            changes.append(f"<strong>Ultimo nome:</strong> {user.last_name} -> {new_last_name}")

        if user.username != new_username:
            changes.append(f"<strong>Ultimo nome:</strong> {user.username} -> {new_username}")

        if user.email != new_email:
            changes.append(f"<strong>Ultimo nome:</strong> {user.email} -> {new_email}")

        user.first_name = new_first_name
        user.last_name = new_last_name
        user.username = new_username
        user.email = new_email

        user.save()

        action = 'Editou o user {} e alterou os seguintes campos:<br>&emsp; {}'.format(user.username,
                                                                                       '<br>&emsp;'.join(changes))
        user_action = UserAction(user=request.user, action=action)
        user_action.save()

        if utilizador.role != utilizador.Role.ADMIN:
            return redirect('ColinaDoSol:dboard_lojistas')

        else:
            return redirect('ColinaDoSol:dboard_perfil')

    context = {
        'user': user,
        'current_page': 'lojistas'
    }
    return render(request, 'ColinaDoSol/Dashboard/Users/dboard-editar-lojista.html', context)


@login_required()
def user_reset_password(request):
    user = request.user
    form = SetPasswordForm(user=request.user)

    if request.method == 'POST':
        form = SetPasswordForm(user=request.user, data=request.POST)
        if form.is_valid():
            # new_password = form.cleaned_data['new_password']

            # user.set_password(str(new_password))
            form.save()
            user.is_first_login = False
            user.save()

            recipient_email = [user.email]
            subject_email = f'Alteração de palavra passe'
            message_email = f'A sua password foi alterada com sucesso'

            send_mail(subject_email, message_email, os.environ.get('DEFAULT_FROM_EMAIL'), recipient_email)

            login(request, user)

            return redirect('ColinaDoSol:dboard_main')
        else:
            print(form.errors)

            for field in form:
                print(f"Field: {field.name}")
                if field.errors:
                    for error in field.errors:
                        print(f"Error: {error}")

    context = {
        'user': User,
        'form': form,
    }
    return render(request, 'ColinaDoSol/setPassword.html', context)


@admin_required
def dboard_delete_user(request, user_id):
    user = User.objects.get(id=user_id)
    action = 'Eliminou o user {} - {}'.format(user.username, user.role)
    user_action = UserAction(user=request.user, action=action)
    user_action.save()
    user.delete()

    return HttpResponseRedirect(reverse('ColinaDoSol:dboard_lojistas'))


@login_required()
def dboard_perfil(request):
    user = request.user
    # logs = UserAction.objects.all()
    logs = LogEntry.objects.all()

    context = {
        'user': user,
        'logs': logs,
        'current_page': 'perfil'

    }

    return render(request, 'ColinaDoSol/Dashboard/Users/dboard-perfil.html', context)


@admin_required
def dboard_lojistas(request):
    admins = User.objects.filter(role=User.Role.ADMIN)
    lojistas = User.objects.filter(role=User.Role.LOJISTA)

    context = {
        'admins': admins,
        'lojistas': lojistas,
        'current_page': 'lojistas'

    }

    return render(request, 'ColinaDoSol/Dashboard/Users/dboard-lojistas.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)

            if user.is_first_login:
                return redirect('ColinaDoSol:dboard_reset_pass')

            return redirect('ColinaDoSol:dboard_main')
        else:
            messages.error(request, "Credenciais Inválidas!")
            return redirect('ColinaDoSol:login')
    else:
        return render(request, 'ColinaDoSol/loginPage.html')


def logout_user(request):
    if request.user.is_authenticated:
        action = 'Fez logout'
        user_action = UserAction(user=request.user, action=action)
        user_action.save()
    logout(request)
    return redirect('ColinaDoSol:index')


def get_user_emails():
    users = User.objects.all()
    emails = [user.email for user in users]
    return emails


@admin_required
def dboard_logs(request):
    logs = UserAction.objects.all()

    context = {
        'logs': logs,
        'current_page': 'logs'
    }

    return render(request, 'ColinaDoSol/Dashboard/Logs/Logs.html', context)

templates/ColinaDoSol/Dashboard/Users/change-password.html
{% extends "ColinaDoSol/login-form-template.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% load custom_filters %}

{% block title %}Change Password Page{% endblock title %}

{% block content %}
    <h2>Alterar Password</h2>
    <br>
    <form method="post">
    {% csrf_token %}
         {% for field in form %}
            <div class="form-outline form-white mb-4">
                {{ field|add_css_class:"form-control form-control-lg" }}
                {{ field.label_tag }}
            </div>
            {% if field.errors %}
                <div class="text-danger">{{ field.errors }}</div>
            {% endif %}
        {% endfor %}
        <input class="btn btn-outline-dark btn-lg px-5" type="submit" value="Submeter">
    </form>
{% endblock content %}

templates/ColinaDoSol/Dashboard/Users/dboard-editar-lojista.html
{% extends "ColinaDoSol/Dashboard/dashboard.html" %}
{% load static %}
{% block content %}
    {% comment %}
    <script src="https://smtpjs.com/v3/smtp.js"></script>
{% endcomment %}

    <div class="col">
        <div class="row  bg-white ">
            <div>
                {% if request.user.role == "ADMIN" or request.user.is_superuser %}
                <a href="{% url 'ColinaDoSol:dboard_lojistas' %}"><i
                        class="fa-solid fa-circle-left backArrow mb-5 backPageBtn"></i></a>
                {% else %}
                    <a href="{% url 'ColinaDoSol:dboard_perfil' %}"><i
                        class="fa-solid fa-circle-left backArrow mb-5 backPageBtn"></i></a>
                {% endif %}
            </div>
            <div>
                <h3 class="pageT">
                    <i class="fa-solid fa-people-group"></i> Editar Utilizador
                </h3>
            </div>
        </div>

        <div class="row" style="padding-top: 18px">
            <form action="" method="POST" class="newUserForm" class="newUserFormId" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col">

                        <div class="mb-3">
                            <label for="first_name" class="form-label"><i
                                    class="fa-solid fa-signature form-input-icon"></i>Primeiro Nome:</label>
                            <input type="text" Required name="first_name" id="first_name" class="form-control"
                                   value="{{ user.first_name }}">
                        </div>

                        <div class="mb-3">
                            <label for="last_name" class="form-label"><i
                                    class="fa-solid fa-signature form-input-icon"></i>Último Nome:</label>
                            <input type="text" Required name="last_name" id="last_name" class="form-control"
                                   value="{{ user.last_name }}">
                        </div>

                        <div class="mb-3">
                            <label for="email" class="form-label"><i
                                    class="fa-solid fa-signature form-input-icon"></i>Email:</label>
                            <input type="email" Required name="email" id="email" class="form-control"
                                   value="{{ user.email }}">
                        </div>

                        <div class="mb-3">
                            <label for="username" class="form-label"><i
                                    class="fa-solid fa-signature form-input-icon"></i>Username:</label>
                            <input type="text" Required id="username" name="username" class="form-control"
                                   value="{{ user.username }}">
                        </div>

                        {% if request.user.is_authenticated and request.user.role == "ADMIN" %}
                            <div class="mb-3">
                                <label for="role" class="form-label"><i
                                        class="fa-solid fa-briefcase form-input-icon"></i>Role:</label>
                                <select name="role" id="role" class="form-select">
                                    <option value="LOJISTA">Lojista</option>
                                    <option value="ADMIN">Administrador</option>
                                </select>
                            </div>
                        {% endif %}



                        <div class="d-flex justify-content-around">
                            <button type="submit" class="btn btn-success" name=""><i
                                    class="fa-solid fa-floppy-disk form-input-icon"></i>Guardar
                            </button>
                            {% if request.user.id == user.id %}
                                <a href="{% url 'ColinaDoSol:change_password' %}"
                                   class="btn btn-outline-success"><i
                                        class="fa-solid fa-pen-to-square form-input-icon"></i>Alterar Password</a>
                            {% endif %}
                            <button type="button" class="btn btn-danger" data-bs-toggle="modal"
                                    data-bs-target="#exampleModal"><i class="fa-solid fa-trash form-input-icon"></i>Eliminar
                            </button>
                        </div>

                    </div>
                </div>
            </form>
        </div>
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Eliminar Lojista</h5>
                        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Quer proceder com a eliminação do lojista "{{ user.username }}"?
                        <p>(Não será possivel desfazer esta operação)</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        <button type="button" class="btn btn-danger"
                                onclick="location.href='{% url 'ColinaDoSol:dboard_delete_user' user.id %}'">Eliminar
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% comment %}
    <script src="{% static 'ColinaDoSol/js/sendCredentials.js' %}"></script>
{% endcomment %}


{% endblock content %}

templates/ColinaDoSol/Dashboard/Users/dboard-lojistas.html
{% extends "ColinaDoSol/Dashboard/dashboard.html" %}
{% load static %}
{% block content %}

    <div class="row storesPage">
        <div class="col storeCol sideSpliter">
            <div class="row">
                <div class="col colTitle">
                    <h3>
                        <i class="fa-solid fa-people-group"></i> Lojistas
                    </h3>
                </div>
                <div class="col top_btns_lojas">
                    <button type="button" class="btn btn-success pull-right"
                            onclick="location.href='{% url 'ColinaDoSol:dboard_novo_user' %}'">
                        <i class="fa-solid fa-plus "></i>Adicionar
                    </button>
                    <!-- <button type="button" class="btn btn-warning pull-right"><i class="fa-solid fa-print"></i>Imprimir</button>
                    -->
                </div>
            </div>

            <div class="storeUL">
                {% include 'ColinaDoSol/Dashboard/DashboardElements/lojistaListItem.html' %}
            </div>

        </div>
        <div class="col storeCol">
            <div class="row">
                <div class="col-8 colTitle">
                    <h3>
                        <i class="fa-solid fa-shield"></i>Administradores
                    </h3>
                </div>
                <div class="col-4 top_btns_lojas">
                    <button type="button" class="btn btn-success pull-right"
                            onclick="location.href='{% url 'ColinaDoSol:dboard_novo_user' %}'">
                        <i class="fa-solid fa-plus "></i>Adicionar
                    </button>
                    <!-- <button type="button" class="btn btn-warning pull-right"><i class="fa-solid fa-print"></i>Imprimir</button>
                    -->
                </div>
            </div>

            <div class="storeUL">
                {% include 'ColinaDoSol/Dashboard/DashboardElements/adminListItem.html' %}
            </div>

        </div>
    </div>




{% endblock content %}

templates/ColinaDoSol/Dashboard/Users/dboard-perfil.html
{% extends "ColinaDoSol/Dashboard/dashboard.html" %}
{% load static %}
{% block content %}

    <div class="row pt-5 storesPage">
        <div class="col">
            <div class="row">
                <div class="col colTitle">
                    <h3>
                        <i class="fa-solid fa-user"></i> Perfil
                    </h3>
                </div>
            </div>

            <div class="card mb-5">
                <div class="card-header">
                    Detalhes do utilizador
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <p><strong>Username:</strong> {{ user.username }}</p>
                            <p><strong>Email:</strong> {{ user.email }}</p>
                            <p><strong>Primeiro Nome:</strong> {{ user.first_name }}</p>
                            <p><strong>Apelido:</strong> {{ user.last_name }}</p>
                        </div>
                        <div class="col-md-6">
                            <p><strong>Privilégios:</strong> {{ user.role }}</p>
                            <p><strong>Data de Criação:</strong> {{ user.date_joined }}</p>
                            <br>
                            <div>
                                <a href="{% url 'ColinaDoSol:dboard_editar_lojista' user.id %}"
                                   class="btn btn-outline-success"><i
                                        class="fa-solid fa-pen-to-square form-input-icon"></i>Editar</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col colTitle">
                    <h3>
                        <i class="fa-solid fa-clock-rotate-left"></i> Histórico
                    </h3>
                </div>
            </div>
            <div class="card mb-5">
                <div class="card-header">
                    Ações do utilizador
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="table-responsive">
                            <table id="actions-table" class="table">
                                <thead>
                                <tr>
                                    <th>User</th>
                                    <th>Action</th>
                                    <th>Date</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for action in user.useraction_set.all %}
                                    <tr>
                                        <td>{{ action.user.username }}</td>
                                        <td>{{ action.action|safe }}</td>
                                        <td>{{ action.date }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css">

    <script>
        $(document).ready(function () {
            $('#actions-table').DataTable({
                "language": {
                    paginate: {
                        next: 'Próxima',
                        previous: 'Anterior',
                    },
                    "search": "Pesquisar:",
                    "lengthMenu": "Apresentar _MENU_ registos por página",
                    "zeroRecords": "Nenhum registo encontrado",
                    "info": "Apresentando _PAGE_ de _PAGES_ páginas",
                    "infoEmpty": "Não existem registos",
                    "infoFiltered": "(filtered from _MAX_ total records)"
                },
                "order": [[2, "desc"]]
            });
        })
        ;
    </script>
{% endblock content %}