ColinaDoSol/urls.py
from django.urls import path, reverse_lazy

from django.contrib.auth import views as auth_views
from .views.site import *
from .views.business import *
from .views.user import *
from .views.store import *
from .views.anuncios import *
from .views.dashboard import *
from .views.content import *

app_name = 'ColinaDoSol'

urlpatterns = [
    path('', index, name='index'),
    path('mapa', mapa, name='mapa'),
    path('dashboard/', dboard_main, name='dboard_main'),
    path('dashboard/perfil/resetPass', user_reset_password, name='dboard_reset_pass'),
    path('dashboard/perfil', dboard_perfil, name='dboard_perfil'),
    path('dashboard/lojistas', dboard_lojistas, name='dboard_lojistas'),
    path('dashboard/novoUser', admin_required(dboard_novo_user), name='dboard_novo_user'),
    path('dashboard/lojas', dboard_lojas, name='dboard_lojas'),
    path('dashboard/anuncios', dboard_anuncios, name='dboard_anuncios'),
    path('dashboard/novaLoja', admin_required(dboard_nova_loja), name='dboard_nova_loja'),
    path('dashboard/novoProduto', dboard_new_product, name='dboard_novo_produto'),
    path('dashboard/editarProduto/<int:produto_id>', dboard_edit_product, name='dboard_editar_produto'),
    path('dashboard/deleteProduto/<int:produto_id>', dboard_delete_product, name='dboard_delete_produto'),
    path('dashboard/novoAnuncio', admin_required(dboard_novo_anuncio), name='dboard_novo_anuncio'),
    path('dashboard/editarAnuncio/<int:anuncio_id>', dboard_editar_anuncio, name='dboard_editar_anuncio'),
    path('dashboard/deleteAnuncio/<int:anuncio_id>', dboard_delete_anuncio, name='dboard_delete_anuncio'),
    path('dashboard/editar/<int:store_id>', dboard_editar_loja, name='dboard_editar_loja'),
    path('dashboard/deleteUser/<int:user_id>', dboard_delete_user, name='dboard_delete_user'),
    path('dashboard/editarUser/<int:user_id>', dboard_editar_user, name='dboard_editar_lojista'),
    path('dashboard/delete/<int:store_id>', dboard_delete_loja, name='dboard_delete_loja'),
    path('login', login_user, name='login'),
    path('logout', logout_user, name='logout'),
    path('businesses', businesses, name='businesses'),
    path('delete/businesses/<int:business_id>', delete_business, name='delete_businesses'),
    path('logs', dboard_logs, name='logs'),
    path('404', custom_404_view, name='custom_404'),
    path('dashboard/content', content, name='content'),
    path('dashboard/content_edit', edit_content, name='edit_content'),
    path('dashboard/content_slider_images', sliderImagesList, name='sliderImagesList'),
    path('dashboard/atualizar_ordem/', atualizar_ordem, name='atualizar_ordem'),
    path('dashboard/adicionar_imagem/', adicionar_imagem, name='adicionar_imagem'),
    path('dashboard/excluir_imagemexcluir_imagem/<int:imagem_id>', excluir_imagem, name='excluir_imagem'),

    # Change Password
    path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='ColinaDoSol/Dashboard/Users/change-password.html',
        success_url='/'), name='change_password'),

    path('password-reset/', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy("ColinaDoSol:password_reset_done"),
        template_name="ColinaDoSol/PasswordManagement/password_reset.html",
        email_template_name='ColinaDoSol/PasswordManagement/password_reset_email.html'
    ), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='ColinaDoSol/PasswordManagement/password_reset_done.html'
    ), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy("ColinaDoSol:password_reset_complete"),
        template_name='ColinaDoSol/PasswordManagement/password_reset_confirm.html'
    ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='ColinaDoSol/PasswordManagement/password_reset_complete.html'
    ), name='password_reset_complete'),
]

prototipo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'ColinaDoSol.views.site.custom_404_view'

urlpatterns = [
    path('', include('ColinaDoSol.urls')),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ColinaDoSol/models.py
import os

from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.conf import settings


class Business(models.Model):
    business = models.CharField(max_length=100)

    def __str__(self):
        return self.business


def get_image_path(instance, filename):
    ext = os.path.splitext(filename)[1]
    filename = f"id{instance.store_num}{ext}"
    return os.path.join('storeLogo/', filename)


class Store(models.Model):
    store_num = models.IntegerField(unique=True)
    image = models.ImageField(upload_to=get_image_path)
    brand = models.CharField('Nome loja', max_length=256)
    business = models.ForeignKey(Business, on_delete=models.DO_NOTHING, null=True)
    phoneNum = models.CharField('Contacto telefónico', max_length=12)
    email = models.CharField('E-mail', max_length=256)
    description = models.TextField('Descrição da loja')
    facebookLink = models.CharField('Link do Facebook', max_length=256, null=True, blank=True)
    instagramLink = models.CharField('Link do Instagram', max_length=256, null=True, blank=True)
    linkedinLink = models.CharField('Link do Linkedin', max_length=256, null=True, blank=True)
    twitterLink = models.CharField('Link do Twitter', max_length=256, null=True, blank=True)
    websiteLink = models.CharField('Link do Website', max_length=256, null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.brand


class OperatingHours(models.Model):
    WEEKDAYS = (
        ('segunda', 'Segunda-feira'),
        ('terca', 'Terça-feira'),
        ('quarta', 'Quarta-feira'),
        ('quinta', 'Quinta-feira'),
        ('sexta', 'Sexta-feira'),
        ('sabado', 'Sábado'),
        ('domingo', 'Domingo'),
        ('feriados', 'Feriados')
    )

    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    weekday = models.CharField(max_length=10, choices=WEEKDAYS)
    opening_time = models.TimeField('Horario de abertura', null=True, blank=True)
    closing_time = models.TimeField('Horario de fecho', null=True, blank=True)
    lunch_start_time = models.TimeField('Início de almoço', null=True, blank=True)
    lunch_end_time = models.TimeField('Fim de almoço', null=True, blank=True)



class Product(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    name = models.CharField('Nome', max_length=128)
    description = models.CharField('Descrção', max_length=512)
    image = models.ImageField(upload_to='uploads/products')


class UserAction(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    action = models.CharField(max_length=1100)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} {self.action} {self.date}'


class User(AbstractUser):
    class Role(models.TextChoices):
        ADMIN = "ADMIN", 'Admin'
        LOJISTA = "LOJISTA", 'Lojista'

    role = models.CharField(max_length=100, choices=Role.choices)
    phone_number = models.CharField(max_length=20, blank=True)
    is_first_login = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Announcement(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title


class SiteConfiguration(models.Model):
    logo = models.ImageField(upload_to='content/ColinaDoSol/img/')
    description = models.TextField()
    facebookLink = models.CharField('Link do Facebook', max_length=256, null=True, blank=True)
    instagramLink = models.CharField('Link do Instagram', max_length=256, null=True, blank=True)


class Imagem(models.Model):
    imagem = models.ImageField(upload_to='uploads/products')
    timestamp = models.DateTimeField(auto_now_add=True)
    ordem = models.PositiveIntegerField(default=0)


class AccessToken(models.Model):
    token = models.CharField(max_length=255)

ColinaDoSol/views/anuncios.py
import os

from django.core.mail import send_mail
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from ColinaDoSol.decorators import admin_required
from ColinaDoSol.models import Announcement, UserAction
from ColinaDoSol.views.user import get_user_emails


def dboard_anuncios(request):
    anuncios = Announcement.objects.all()
    return render(request, 'ColinaDoSol/Dashboard/Anuncios/dboard-anuncios.html',
                  {'anuncios': anuncios, 'current_page': 'anuncios'})


@admin_required
def dboard_novo_anuncio(request):
    if request.method == "POST":
        title = request.POST.get('title')
        text = request.POST.get('text')

        anuncio = Announcement(title=title, text=text, user=request.user)

        # send email
        recipient_email = get_user_emails()
        subject = f'Anuncio - {title}'
        message = f'{text}'

        send_mail(subject, message, os.environ.get('DEFAULT_FROM_EMAIL'), recipient_email)

        anuncio.save()

        action = 'Criou um novo anuncio {}'.format(anuncio.title)
        user_action = UserAction(user=request.user, action=action)
        user_action.save()

        anuncios = Announcement.objects.all()

        context = {
            'anuncios': anuncios,
            'current_page': 'anuncios'
        }

        return render(request, 'ColinaDoSol/Dashboard/Anuncios/dboard-anuncios.html', context)
    return render(request, 'ColinaDoSol/Dashboard/Anuncios/dboard-novo-anuncio.html', {'current_page': 'anuncios'})


@admin_required
def dboard_editar_anuncio(request, anuncio_id):
    anuncio = get_object_or_404(Announcement, id=anuncio_id)
    user = request.user

    if user.role != user.Role.ADMIN and anuncio.user != user:
        raise Http404("This page does not exist")

    if request.method == "POST":
        title = request.POST.get('title')
        text = request.POST.get('text')

        changed_fields = []

        old_values = {}  # Store old values here

        if anuncio.title != title:
            changed_fields.append('title')
            old_values['title'] = anuncio.title  # Store old value of 'title'
            anuncio.title = title

        if anuncio.text != text:
            changed_fields.append('text')
            old_values['text'] = anuncio.text  # Store old value of 'text'
            anuncio.text = text

        anuncio.save()

        if changed_fields:
            change_logs = []
            for field in changed_fields:
                change_logs.append(
                    "Campo '{}' alterado: '{}' -> '{}'".format(field, old_values[field], getattr(anuncio, field)))

            action = 'Editou o anuncio {} - {}'.format(anuncio.title, ', '.join(change_logs))
            user_action = UserAction(user=request.user, action=action)
            user_action.save()

        return redirect('ColinaDoSol:dboard_anuncios')

    context = {
        'anuncio': anuncio,
        'current_page': 'anuncios'
    }

    return render(request, 'ColinaDoSol/Dashboard/Anuncios/dboard-editar-anuncio.html', context)


@admin_required
def dboard_delete_anuncio(request, anuncio_id):
    anuncio = Announcement.objects.get(id=anuncio_id)
    action = 'Eliminou o anuncio {}'.format(anuncio.title)
    user_action = UserAction(user=request.user, action=action)
    user_action.save()
    anuncio.delete()

    return HttpResponseRedirect(reverse('ColinaDoSol:dboard_anuncios'))

ColinaDoSol/views/business.py
from django.shortcuts import get_object_or_404, redirect, render

from ColinaDoSol.forms import BusinessForm
from ColinaDoSol.models import Business, UserAction


def businesses(request):
    businessList = Business.objects.all()
    success_message = ""

    if request.method == 'POST':
        if 'business_id' in request.POST:
            # Edit existing business
            business_id = request.POST.get('business_id')
            business = get_object_or_404(Business, id=business_id)
            form = BusinessForm(request.POST, instance=business)
            if form.is_valid():
                form.save()
                success_message = "Ramo editado com sucesso!"


                return redirect('ColinaDoSol:businesses')  # Redirect after successful form submission
        else:
            form = BusinessForm(request.POST)
            if form.is_valid():
                business = form.save()

                action = 'Eliminou o ramo de negocio {}'.format(business.business)
                user_action = UserAction(user=request.user, action=action)
                user_action.save()

                success_message = "Ramo criado com sucesso!"
                return redirect('ColinaDoSol:businesses')  # Redirect after successful form submission
    else:
        form = BusinessForm()

    context = {
        'form': form,
        'businessList': businessList,
        'success_message': success_message,
        'current_page': 'ramos'
    }
    return render(request, 'ColinaDoSol/Dashboard/Ramos/ramos-atividade.html', context)


def delete_business(request, business_id):
    business = get_object_or_404(Business, id=business_id)
    business.delete()

    action = 'Eliminou o ramo de negocio {}'.format(business.business)
    user_action = UserAction(user=request.user, action=action)
    user_action.save()

    return redirect('ColinaDoSol:businesses')

ColinaDoSol/views/content.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from ColinaDoSol.models import SiteConfiguration, Imagem
from ColinaDoSol.forms import SiteConfigurationForm, ImagemForm


@login_required
def edit_content(request):
    site_settings_obj = SiteConfiguration.objects.first()  # Assuming there is only one SiteSettings object

    if request.method == 'POST':
        form = SiteConfigurationForm(request.POST, request.FILES, instance=site_settings_obj)
        if form.is_valid():
            form.save()

            return redirect('ColinaDoSol:content')  # Redirect to the homepage or any desired URL after saving
    else:
        form = SiteConfigurationForm(instance=site_settings_obj)
    return render(request, 'ColinaDoSol/Dashboard/SiteContent/content_edit.html',
                  {'form': form, 'current_page': 'conteudos'})


@login_required
def content(request):
    site_content = SiteConfiguration.objects.first()
    imagens = Imagem.objects.all().order_by('ordem')

    return render(request, 'ColinaDoSol/Dashboard/SiteContent/content.html',
                  {'content': site_content, 'current_page': 'conteudos', 'imagens': imagens})


@login_required
def sliderImagesList(request):
    imagens = Imagem.objects.all().order_by('ordem')

    return render(request, 'ColinaDoSol/Dashboard/SiteContent/imagensLista.html',
                  {'imagens': imagens, 'current_page': 'conteudos'})


from django.http import JsonResponse


@login_required
def atualizar_ordem(request):
    if request.method == 'POST':
        nova_ordem = request.POST.getlist('ordem[]')  # Obter a nova ordem dos itens da requisição POST

        for posicao, imagem_id in enumerate(nova_ordem):
            imagem = Imagem.objects.get(id=imagem_id)
            imagem.ordem = posicao
            imagem.save()

        # Retornar uma resposta JSON indicando sucesso
        data = {'success': True}
        return JsonResponse(data)

    # Se a requisição não for do tipo POST, retornar uma resposta JSON indicando erro
    data = {'success': False, 'error': 'Método inválido'}
    return JsonResponse(data)


@login_required
def adicionar_imagem(request):
    if request.method == 'POST':
        form = ImagemForm(request.POST, request.FILES)
        if form.is_valid():
            imagem = form.save(commit=False)

            # Definir a ordem da nova imagem
            imagem.ordem = Imagem.objects.count()

            imagem.save()

            # Atualizar a posição de todas as imagens
            imagens = Imagem.objects.all().order_by('ordem')
            for posicao, imagem in enumerate(imagens):
                imagem.ordem = posicao
                imagem.save()

            return redirect('ColinaDoSol:sliderImagesList')

    else:
        form = ImagemForm()

    return render(request, 'ColinaDoSol/Dashboard/SiteContent/addImagemLista.html',
                  {'form': form, 'current_page': 'conteudos'})


@login_required
def excluir_imagem(request, imagem_id):
    imagem = get_object_or_404(Imagem, id=imagem_id)
    ordem_atual = imagem.ordem

    imagem.delete()

    # Atualizar a ordem após a exclusão
    imagens = Imagem.objects.filter(ordem__gt=ordem_atual).order_by('ordem')
    for posicao, imagem in enumerate(imagens, start=ordem_atual):
        imagem.ordem = posicao
        imagem.save()

    return redirect('ColinaDoSol:sliderImagesList')

templates/ColinaDoSol/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>CC Colina do Sol</title>

    <link rel="stylesheet" href="{% static 'ColinaDoSol/css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'ColinaDoSol/css/stores.css' %}">
    <link rel="stylesheet" href="{% static 'ColinaDoSol/css/contacts.css' %}">
    <link rel="stylesheet" href="{% static 'ColinaDoSol/css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'ColinaDoSol/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'ColinaDoSol/css/heroSlider.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'ColinaDoSol/img/favicon.ico' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20,100,1,200"
          rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,300;0,400;0,500;0,700;0,900;1,300;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>

<nav class="topmenu navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    {% block icon %}
    {% endblock %}

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url "ColinaDoSol:index" %}#heroCarousel">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "ColinaDoSol:index" %}#news-section">Notícias</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "ColinaDoSol:index" %}#mapa-section">Lojas</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "ColinaDoSol:index" %}#contactos-section">Contactos</a>
            </li>
        </ul>
    </div>
</nav>

{% block content %}{% endblock content %}

<script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>

</body>

<footer class="text-center text-lg-start text-white" style="background-color: #3e4551">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
        <!-- Section: Links -->
        <section class="">
            <!--Grid row-->
            <div class="row">
                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Centro Comercial Colina do Sol</h5>
                    {% block descricao %}
                    {% endblock %}
                </div>
                <!--Grid column-->
                <div class="col"></div>
                <!--Grid column-->
                <div class="col-lg-2 col-md-6 mb-4 mb-md-0">

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-2 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Redes Sociais</h5>

                    <ul class="list-unstyled mb-0">
                        {% block redesSociais %}
                        {% endblock %}
                    </ul>
                </div>
                <!--Grid column-->
            </div>
            <!--Grid row-->
        </section>
        <br>
    </div>

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
        © 2020 Copyright:
        <a class="text-white" href="{% url 'ColinaDoSol:dboard_main' %}">"ccColinaDoSol"</a>
    </div>
    <!-- Copyright -->
</footer>

</html>

templates/ColinaDoSol/storeModal.html
<!-- Modal -->
<div class="modal fade" id="id{{ loja.store_num }}" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalCenterTitle">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <div>
                    <h4 class="modal-title" id="exampleModalLongTitle">{{ loja.brand }}</h4>
                    <p>{{ loja.business }}</p>
                </div>


                <button type="button" class="btn-close" data-bs-dismiss="modal"
                        aria-label="Close"></button>
            </div>

            <div class="modal-body">
                    <div class="d-flex ">
                        <img src="{{ loja.image.url }}" class="mx-auto mb-2" alt="{{ loja.brand }}"
                         style="border-radius: 0; max-width: 200px">
                    </div>



                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Descrição</h5>
                        <p class="card-text text-justify">{{ loja.description }}</p>
                    </div>
                </div>
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Horário</h5>
                        {% for operating_hour in loja.operatinghours_set.all %}
                            <div class="row">
                                <div class="col"><p>{{ operating_hour.get_weekday_display }}</p></div>
                                <div class="col">
                                    {% if operating_hour.opening_time and operating_hour.closing_time %}
                                        {% if operating_hour.lunch_start_time and operating_hour.lunch_end_time %}
                                            <p>{{ operating_hour.opening_time|time:'H:i' }} -
                                                {{ operating_hour.lunch_start_time|time:'H:i' }} &nbsp;&nbsp;&nbsp;&nbsp;
                                                {{ operating_hour.lunch_end_time|time:'H:i' }} -
                                                {{ operating_hour.closing_time|time:'H:i' }}</p>
                                        {% else %}
                                            <p>{{ operating_hour.opening_time|time:'H:i' }}
                                                - {{ operating_hour.closing_time|time:'H:i' }}</p>
                                        {% endif %}
                                    {% else %}
                                        <p>Encerrado</p>
                                    {% endif %}
                                </div>
                            </div>
                            {% empty %}
                            <li>Não existe horário.</li>
                        {% endfor %}
                    </div>
                </div>

                {% if loja.product_set.all.count > 0 %}
                    <h5>Produtos/Serviços:</h5>
                    <div class="container-fluid">
                        <div class="row flex-nowrap overflow-auto">
                            {% for product in loja.product_set.all %}
                                <div class="col-md-4">
                                    <div class="card d-flex flex-fill h-100">
                                        <img src="{{ product.image.url }}" class="card-img-top p-2"
                                             alt="{{ product.name }}">
                                        <div class="card-body d-flex flex-column">
                                            <h5 class="card-title">{{ product.name }}</h5>
                                            <p class="card-text">{{ product.description }}</p>
                                            <div class="mt-auto"></div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
            </div>
            <hr>
            <div class="row">
                <h5>Contactos</h5>

                <div class="col">
                    <p>Telefone: {{ loja.phoneNum }}</p>
                </div>
                <div class="col">
                    <p>E-mail: {{ loja.email }}</p>
                </div>
            </div>
            <div class="row">
                {% if loja.facebookLink != null and loja.facebookLink != "None" and loja.facebookLink != "" %}
                    <div class="col text-center">
                        <a class="btn btn-floating m-1" href="{{ loja.facebookLink }}" role="button"
                           target="_blank">
                            <i class="fa-brands fa-facebook"></i>
                        </a>
                    </div>

                {% endif %}
                {% if loja.instagramLink != null and loja.instagramLink != "None" and loja.instagramLink != "" %}
                    <div class="col text-center">

                        <a class="btn btn-floating m-1" href="{{ loja.instagramLink }}"
                           role="button"
                           target="_blank">
                            <i class="fa-brands fa-instagram"></i>

                        </a>
                    </div>
                {% endif %}
                {% if loja.linkedinLink != null and loja.linkedinLink != "None" and loja.linkedinLink != "" %}
                    <div class="col text-center">

                        <a class="btn btn-floating m-1" href="{{ loja.linkedinLink }}"
                           role="button"
                           target="_blank">
                            <i class="fa-brands fa-linkedin"></i>

                        </a>
                    </div>
                {% endif %}
                {% if loja.twitterLink != null and loja.twitterLink != "None" and loja.twitterLink != "" %}
                    <div class="col text-center">

                        <a class="btn btn-floating m-1" href="{{ loja.twitterLink }}"
                           role="button"
                           target="_blank">
                            <i class="fa-brands fa-twitter"></i>

                        </a>
                    </div>
                {% endif %}

                {% if loja.websiteLink != null and loja.websiteLink != "None" and loja.websiteLink != "" %}
                    <div class="col text-center">

                        <a class="btn btn-floating m-1" href="{{ loja.websiteLink }}" role="button"
                           target="_blank">
                            <i class="fa-solid fa-magnifying-glass"></i>
                            website
                        </a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>