ColinaDoSol/urls.py
from django.urls import path, reverse_lazy

from django.contrib.auth import views as auth_views
from .views.site import *
from .views.business import *
from .views.user import *
from .views.store import *
from .views.anuncios import *
from .views.dashboard import *
from .views.content import *

app_name = 'ColinaDoSol'

urlpatterns = [
    path('', index, name='index'),
    path('mapa', mapa, name='mapa'),
    path('dashboard/', dboard_main, name='dboard_main'),
    path('dashboard/perfil/resetPass', user_reset_password, name='dboard_reset_pass'),
    path('dashboard/perfil', dboard_perfil, name='dboard_perfil'),
    path('dashboard/lojistas', dboard_lojistas, name='dboard_lojistas'),
    path('dashboard/novoUser', admin_required(dboard_novo_user), name='dboard_novo_user'),
    path('dashboard/lojas', dboard_lojas, name='dboard_lojas'),
    path('dashboard/anuncios', dboard_anuncios, name='dboard_anuncios'),
    path('dashboard/novaLoja', admin_required(dboard_nova_loja), name='dboard_nova_loja'),
    path('dashboard/novoProduto', dboard_new_product, name='dboard_novo_produto'),
    path('dashboard/editarProduto/<int:produto_id>', dboard_edit_product, name='dboard_editar_produto'),
    path('dashboard/deleteProduto/<int:produto_id>', dboard_delete_product, name='dboard_delete_produto'),
    path('dashboard/novoAnuncio', admin_required(dboard_novo_anuncio), name='dboard_novo_anuncio'),
    path('dashboard/editarAnuncio/<int:anuncio_id>', dboard_editar_anuncio, name='dboard_editar_anuncio'),
    path('dashboard/deleteAnuncio/<int:anuncio_id>', dboard_delete_anuncio, name='dboard_delete_anuncio'),
    path('dashboard/editar/<int:store_id>', dboard_editar_loja, name='dboard_editar_loja'),
    path('dashboard/deleteUser/<int:user_id>', dboard_delete_user, name='dboard_delete_user'),
    path('dashboard/editarUser/<int:user_id>', dboard_editar_user, name='dboard_editar_lojista'),
    path('dashboard/delete/<int:store_id>', dboard_delete_loja, name='dboard_delete_loja'),
    path('login', login_user, name='login'),
    path('logout', logout_user, name='logout'),
    path('businesses', businesses, name='businesses'),
    path('delete/businesses/<int:business_id>', delete_business, name='delete_businesses'),
    path('logs', dboard_logs, name='logs'),
    path('404', custom_404_view, name='custom_404'),
    path('dashboard/content', content, name='content'),
    path('dashboard/content_edit', edit_content, name='edit_content'),
    path('dashboard/content_slider_images', sliderImagesList, name='sliderImagesList'),
    path('dashboard/atualizar_ordem/', atualizar_ordem, name='atualizar_ordem'),
    path('dashboard/adicionar_imagem/', adicionar_imagem, name='adicionar_imagem'),
    path('dashboard/excluir_imagemexcluir_imagem/<int:imagem_id>', excluir_imagem, name='excluir_imagem'),

    # Change Password
    path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='ColinaDoSol/Dashboard/Users/change-password.html',
        success_url='/'), name='change_password'),

    path('password-reset/', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy("ColinaDoSol:password_reset_done"),
        template_name="ColinaDoSol/PasswordManagement/password_reset.html",
        email_template_name='ColinaDoSol/PasswordManagement/password_reset_email.html'
    ), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='ColinaDoSol/PasswordManagement/password_reset_done.html'
    ), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy("ColinaDoSol:password_reset_complete"),
        template_name='ColinaDoSol/PasswordManagement/password_reset_confirm.html'
    ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='ColinaDoSol/PasswordManagement/password_reset_complete.html'
    ), name='password_reset_complete'),
]

prototipo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'ColinaDoSol.views.site.custom_404_view'

urlpatterns = [
    path('', include('ColinaDoSol.urls')),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ColinaDoSol/views/anuncios.py
import os

from django.core.mail import send_mail
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from ColinaDoSol.decorators import admin_required
from ColinaDoSol.models import Announcement, UserAction
from ColinaDoSol.views.user import get_user_emails


def dboard_anuncios(request):
    anuncios = Announcement.objects.all()
    return render(request, 'ColinaDoSol/Dashboard/Anuncios/dboard-anuncios.html',
                  {'anuncios': anuncios, 'current_page': 'anuncios'})


@admin_required
def dboard_novo_anuncio(request):
    if request.method == "POST":
        title = request.POST.get('title')
        text = request.POST.get('text')

        anuncio = Announcement(title=title, text=text, user=request.user)

        # send email
        recipient_email = get_user_emails()
        subject = f'Anuncio - {title}'
        message = f'{text}'

        send_mail(subject, message, os.environ.get('DEFAULT_FROM_EMAIL'), recipient_email)

        anuncio.save()

        action = 'Criou um novo anuncio {}'.format(anuncio.title)
        user_action = UserAction(user=request.user, action=action)
        user_action.save()

        anuncios = Announcement.objects.all()

        context = {
            'anuncios': anuncios,
            'current_page': 'anuncios'
        }

        return render(request, 'ColinaDoSol/Dashboard/Anuncios/dboard-anuncios.html', context)
    return render(request, 'ColinaDoSol/Dashboard/Anuncios/dboard-novo-anuncio.html', {'current_page': 'anuncios'})


@admin_required
def dboard_editar_anuncio(request, anuncio_id):
    anuncio = get_object_or_404(Announcement, id=anuncio_id)
    user = request.user

    if user.role != user.Role.ADMIN and anuncio.user != user:
        raise Http404("This page does not exist")

    if request.method == "POST":
        title = request.POST.get('title')
        text = request.POST.get('text')

        changed_fields = []

        old_values = {}  # Store old values here

        if anuncio.title != title:
            changed_fields.append('title')
            old_values['title'] = anuncio.title  # Store old value of 'title'
            anuncio.title = title

        if anuncio.text != text:
            changed_fields.append('text')
            old_values['text'] = anuncio.text  # Store old value of 'text'
            anuncio.text = text

        anuncio.save()

        if changed_fields:
            change_logs = []
            for field in changed_fields:
                change_logs.append(
                    "Campo '{}' alterado: '{}' -> '{}'".format(field, old_values[field], getattr(anuncio, field)))

            action = 'Editou o anuncio {} - {}'.format(anuncio.title, ', '.join(change_logs))
            user_action = UserAction(user=request.user, action=action)
            user_action.save()

        return redirect('ColinaDoSol:dboard_anuncios')

    context = {
        'anuncio': anuncio,
        'current_page': 'anuncios'
    }

    return render(request, 'ColinaDoSol/Dashboard/Anuncios/dboard-editar-anuncio.html', context)


@admin_required
def dboard_delete_anuncio(request, anuncio_id):
    anuncio = Announcement.objects.get(id=anuncio_id)
    action = 'Eliminou o anuncio {}'.format(anuncio.title)
    user_action = UserAction(user=request.user, action=action)
    user_action.save()
    anuncio.delete()

    return HttpResponseRedirect(reverse('ColinaDoSol:dboard_anuncios'))

ColinaDoSol/views/business.py
from django.shortcuts import get_object_or_404, redirect, render

from ColinaDoSol.forms import BusinessForm
from ColinaDoSol.models import Business, UserAction


def businesses(request):
    businessList = Business.objects.all()
    success_message = ""

    if request.method == 'POST':
        if 'business_id' in request.POST:
            # Edit existing business
            business_id = request.POST.get('business_id')
            business = get_object_or_404(Business, id=business_id)
            form = BusinessForm(request.POST, instance=business)
            if form.is_valid():
                form.save()
                success_message = "Ramo editado com sucesso!"


                return redirect('ColinaDoSol:businesses')  # Redirect after successful form submission
        else:
            form = BusinessForm(request.POST)
            if form.is_valid():
                business = form.save()

                action = 'Eliminou o ramo de negocio {}'.format(business.business)
                user_action = UserAction(user=request.user, action=action)
                user_action.save()

                success_message = "Ramo criado com sucesso!"
                return redirect('ColinaDoSol:businesses')  # Redirect after successful form submission
    else:
        form = BusinessForm()

    context = {
        'form': form,
        'businessList': businessList,
        'success_message': success_message,
        'current_page': 'ramos'
    }
    return render(request, 'ColinaDoSol/Dashboard/Ramos/ramos-atividade.html', context)


def delete_business(request, business_id):
    business = get_object_or_404(Business, id=business_id)
    business.delete()

    action = 'Eliminou o ramo de negocio {}'.format(business.business)
    user_action = UserAction(user=request.user, action=action)
    user_action.save()

    return redirect('ColinaDoSol:businesses')

ColinaDoSol/views/content.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from ColinaDoSol.models import SiteConfiguration, Imagem
from ColinaDoSol.forms import SiteConfigurationForm, ImagemForm


@login_required
def edit_content(request):
    site_settings_obj = SiteConfiguration.objects.first()  # Assuming there is only one SiteSettings object

    if request.method == 'POST':
        form = SiteConfigurationForm(request.POST, request.FILES, instance=site_settings_obj)
        if form.is_valid():
            form.save()

            return redirect('ColinaDoSol:content')  # Redirect to the homepage or any desired URL after saving
    else:
        form = SiteConfigurationForm(instance=site_settings_obj)
    return render(request, 'ColinaDoSol/Dashboard/SiteContent/content_edit.html',
                  {'form': form, 'current_page': 'conteudos'})


@login_required
def content(request):
    site_content = SiteConfiguration.objects.first()
    imagens = Imagem.objects.all().order_by('ordem')

    return render(request, 'ColinaDoSol/Dashboard/SiteContent/content.html',
                  {'content': site_content, 'current_page': 'conteudos', 'imagens': imagens})


@login_required
def sliderImagesList(request):
    imagens = Imagem.objects.all().order_by('ordem')

    return render(request, 'ColinaDoSol/Dashboard/SiteContent/imagensLista.html',
                  {'imagens': imagens, 'current_page': 'conteudos'})


from django.http import JsonResponse


@login_required
def atualizar_ordem(request):
    if request.method == 'POST':
        nova_ordem = request.POST.getlist('ordem[]')  # Obter a nova ordem dos itens da requisição POST

        for posicao, imagem_id in enumerate(nova_ordem):
            imagem = Imagem.objects.get(id=imagem_id)
            imagem.ordem = posicao
            imagem.save()

        # Retornar uma resposta JSON indicando sucesso
        data = {'success': True}
        return JsonResponse(data)

    # Se a requisição não for do tipo POST, retornar uma resposta JSON indicando erro
    data = {'success': False, 'error': 'Método inválido'}
    return JsonResponse(data)


@login_required
def adicionar_imagem(request):
    if request.method == 'POST':
        form = ImagemForm(request.POST, request.FILES)
        if form.is_valid():
            imagem = form.save(commit=False)

            # Definir a ordem da nova imagem
            imagem.ordem = Imagem.objects.count()

            imagem.save()

            # Atualizar a posição de todas as imagens
            imagens = Imagem.objects.all().order_by('ordem')
            for posicao, imagem in enumerate(imagens):
                imagem.ordem = posicao
                imagem.save()

            return redirect('ColinaDoSol:sliderImagesList')

    else:
        form = ImagemForm()

    return render(request, 'ColinaDoSol/Dashboard/SiteContent/addImagemLista.html',
                  {'form': form, 'current_page': 'conteudos'})


@login_required
def excluir_imagem(request, imagem_id):
    imagem = get_object_or_404(Imagem, id=imagem_id)
    ordem_atual = imagem.ordem

    imagem.delete()

    # Atualizar a ordem após a exclusão
    imagens = Imagem.objects.filter(ordem__gt=ordem_atual).order_by('ordem')
    for posicao, imagem in enumerate(imagens, start=ordem_atual):
        imagem.ordem = posicao
        imagem.save()

    return redirect('ColinaDoSol:sliderImagesList')

ColinaDoSol/views/dashboard.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from ColinaDoSol.models import Announcement, User, Store


@login_required
def dboard_main(request):
    anunciosList = Announcement.objects.all()

    if request.user.role == User.Role.ADMIN or request.user.is_superuser:
        lojasList = Store.objects.all()
        lojistas = User.objects.filter(role=User.Role.LOJISTA)
        context = {'lojasList': lojasList[:3], 'lojistas': lojistas[:3], 'anuncios': anunciosList, 'current_page': 'dashboard'}

    else:
        lojasList = Store.objects.filter(user=request.user)
        context = {'lojasList': lojasList[:3], 'anuncios': anunciosList, 'current_page': 'dashboard'}
    return render(request, 'ColinaDoSol/Dashboard/dboard-main.html', context)

templates/ColinaDoSol/Dashboard/dashboard.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>CC Colina do Sol</title>
    <link rel="stylesheet" href="{% static 'ColinaDoSol/css/sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'ColinaDoSol/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'ColinaDoSol/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'ColinaDoSol/css/dashboard.css' %}">

    <link rel="icon" type="image/x-icon" href="{% static 'ColinaDoSol/img/favicon.ico' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,300;0,400;0,500;0,700;0,900;1,300;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet">


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.css">
    <script src="{% static 'ColinaDoSol/js/equal-hours-values.js' %}"></script>
</head>
<body>
<div class="wrapper">
    <!-- Sidebar  -->
    <nav id="sidebar" class="ps-2">
        <div class="sidebar-header">
            <img src="{% static 'ColinaDoSol/img/logos/logoVpreto.png' %}" style="max-width: 100%; height: auto;"
                 alt="logo">
        </div>
        <ul class="list-unstyled components">
            {% if request.user.is_authenticated and request.user.role == "ADMIN" or request.user.is_superuser %}
                <h3 class="text-center">Gestão</h3>
            {% endif %}
            {% if request.user.is_authenticated and request.user.role == "LOJISTA" %}
                <h3 class="text-center">Lojista</h3>
            {% endif %}
            <li>
                <h5>
                    <a href="{% url 'ColinaDoSol:dboard_main' %}"
                       {% if current_page == 'dashboard' %}class="active_page"{% endif %}><i
                            class="fas fa-columns icon-text"></i>Dashboard</a>
                </h5>
            </li>
            <li>
                <h5>
                    <a href="{% url 'ColinaDoSol:dboard_anuncios' %}"
                       {% if current_page == 'anuncios' %}class="active_page"{% endif %}><i
                            class="fas fa-bullhorn icon-text"></i>Anúncios</a>
                </h5>
            </li>
            <li>
                <h5>
                    <a href="{% url 'ColinaDoSol:dboard_lojas' %}"
                       {% if current_page == 'lojas' %}class="active_page"{% endif %}><i
                            class="fa-solid fa-shop icon-text"></i>Lojas</a>
                </h5>
            </li>
        </ul>
        {% if request.user.is_authenticated and request.user.role == "ADMIN" or request.user.is_superuser %}
            <ul class="list-unstyled components">
                <h4>Gestão</h4>
                <li>
                    <h5>
                        <a href="{% url 'ColinaDoSol:dboard_lojistas' %}"
                           {% if current_page == 'lojistas' %}class="active_page"{% endif %}><i
                                class="fa-solid fa-people-group icon-text"></i>Lojistas</a>
                    </h5>
                </li>
                <li>
                    <h5>
                        <a href="{% url 'ColinaDoSol:logs' %}"
                           {% if current_page == 'logs' %}class="active_page"{% endif %}><i
                                class="fa-solid fa-history icon-text"></i>Atividade</a>
                    </h5>
                </li>
                <li>
                    <h5>
                        <a href="{% url 'ColinaDoSol:businesses' %}"
                           {% if current_page == 'ramos' %}class="active_page"{% endif %}>
                            <i class="fa-solid fa-tag icon-text"></i>Ramos</a>
                    </h5>
                </li>
            </ul>
            <ul class="list-unstyled components">
                <h4>Website</h4>
                <li>
                    <h5>
                        <a href="{% url 'ColinaDoSol:content' %}"
                           {% if current_page == 'conteudos' %}class="active_page"{% endif %}>
                            <i class="fas fa-desktop icon-text "></i>Conteúdos</a>
                    </h5>

                </li>
            </ul>
        {% endif %}

        <ul class="list-unstyled CTAs">
            <li>
                <a href="{% url 'ColinaDoSol:index' %}" class="article"><i class="fas fa-undo icon-text"></i>Voltar para
                    site</a>
            </li>
        </ul>
    </nav>

    <!-- Page Content  -->
    <div id="content">
        <nav class="navbar navbar-expand-lg navbar-light bg-light pr-4 shadow-sm">
            <button type="button" id="sidebarCollapse" class="btn btn-white">
                <i class="fas fa-align-left"></i>
                <span>Menu</span>
            </button>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item me-3">
                    <a class="btn navbar-btn {% if current_page == 'perfil' %}navbar-btn-clicked{% endif %}"
                       href="{% url 'ColinaDoSol:dboard_perfil' %}">
                        <i class="fas fa-user-circle icon-text"></i>Perfil
                    </a>
                </li>
                <li class="nav-item me-3">
                    <a class="btn navbar-btn logout-btn" href="{% url 'ColinaDoSol:logout' %}">
                        <i class="fas fa-sign-out-alt icon-text"></i>Logout
                    </a>
                </li>
            </ul>
        </nav>
        <div class="px-5 py-2">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

<script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js"></script>
<script>
    $('#sidebarCollapse').on('click', function () {
        $('#sidebar').toggleClass('active');
    });
</script>

{% block scripts %}
{% endblock %}
</body>

</html>

templates/ColinaDoSol/Dashboard/dboard-main.html
{% extends "ColinaDoSol/Dashboard/dashboard.html" %}
{% load static %}
{% block content %}

    <div class="row m-0">
        <div class="col sideSpliter">
            <div class="row">
                <div class="col colTitle">
                    <h3>
                        <i class="fa-solid fa-bullhorn"></i> Anúncios
                    </h3>
                </div>
                <!--<div class="col">
                    <button type="button" class="btn btn-success pull-right" onclick="">
                        <i class="fa-solid fa-plus"></i>Adicionar
                    </button>
                    <button type="button" class="btn btn-warning pull-right"><i class="fa-solid fa-print"></i>Imprimir
                    </button>
                </div>-->
            </div>
            <!--ANÚNCIOS-->

            <div class="storeUL">
                {% include 'ColinaDoSol/Dashboard/DashboardElements/anuncioListItem.html' %}
            </div>
            <!--FIM ANÚNCIOS-->
        </div>
        <div class="col">
            <div class="row">
                <h3 class="pageT">
                    <i class="fa-solid fa-shop"></i> Lojas
                </h3>
                <!--LOJAS-->
                {% include 'ColinaDoSol/Dashboard/DashboardElements/storeListItem.html' %}

                <div class="mb-3 d-flex">
                    <button type="button" class="btn btn-success" style="margin: auto;"
                            onclick="location.href='{% url 'ColinaDoSol:dboard_lojas' %}'">
                        Ver mais...
                    </button>
                </div>

                <!--FIM LOJAS-->
            </div>

            {% if request.user.role == "ADMIN" or request.user.is_superuser %}
                <div class="row">
                    <h3 class="pageT">
                        <i class="fa-solid fa-people-group"></i> Lojistas
                    </h3>
                    <div class="storeUL">
                        {% include 'ColinaDoSol/Dashboard/DashboardElements/lojistaListItem.html' %}
                    </div>
                    <div class="mb-3 d-flex">
                        <button type="button" class="btn btn-success" style="margin: auto;"
                                onclick="location.href='{% url 'ColinaDoSol:dboard_lojistas' %}'">
                            Ver mais...
                        </button>
                    </div>


                </div>
            {% endif %}
        </div>
    </div>


{% endblock content %}